### ISSUE TITLE
'PN532' does not name a type

### ISSUE THREAD

**Issue by xwareinnovations** [Robotto/ESPnfc#1]
Arduino 1.8.7 throwing the error 'PN532' does not name a type on this line
PN532 nfc(pn532spi);

**Comment by Robotto** [comment]
Did you install the PN532 libraries from https://github.com/Seeed-Studio/PN532 ?
#include <PN532_SPI.h>
#include <PN532.h>

**Comment by Robotto** [comment]
I'll await a reply for another week, and then close.

**Comment by xwareinnovations** [comment]
I think that error finally went away

**Comment by Robotto** [comment]
Good job.
